<div class="static">
 <h3>Promozioni </h3>
 
  ID staff <?= $this->idstaff ?>

 <h4> Ordine per la data di scadenza </h4>
 <div>
 <?php 
 echo '<table class="tabella">';
	echo "<tr><th>Codice</th><th>Tipo</th><th>Data Inizio</th><th>Data Fine</th><th>Prodotto</th><th>Categoria</th><th>Descrizione</th><th>Immagine</th><th>Azienda</th><th>Prezzo</th><th>Modifica</th><th>Cancella</th></tr>";
  foreach ($this->prodotto as $prodotto) {
      echo "<tr><td>".$prodotto->cod_promozione."</td>"
              . "<td>".$prodotto->tipo_prom."</td>"
              . "<td>".$prodotto->data_inizio."</td>"
              . "<td>".$prodotto->data_fine."</td>"
              . "<td>".$prodotto->prodotto."</td>"
              . "<td>".$prodotto->name."</td>"
              . "<td>".$prodotto->descrizione_prom."</td>"
              . "<td>".$prodotto->immagine."</td>"
              . "<td>".$prodotto->nome."</td>"
              . "<td>".$prodotto->prezzo_unitario_prod." € </td>"
              . "<td><a href=" . $this->url(array('controller' => 'staff',
                                                        'action' => 'modificapromo',
                                                        'codprod'=> $prodotto->cod_promozione), 
                                                        'default', true) ."><img class='icon' src='".$this->baseUrl('images/modifica.png')."' alt='Modifica'></a></td>"
              . "<td><a href=" . $this->url(array('controller' => 'staff',
                                                        'action' => 'cancella',
                                                        'codprod'=> $prodotto->cod_promozione), 
                                                        'default', true) ."><img class='icon' src='".$this->baseUrl('images/cancella.png')."' alt='Cancella'></a></td></tr>";
  }
 echo '</table>';
 ?>
 

  <?php if($this->prodotto instanceof Zend_Paginator) {
                            echo $this->paginationControl($this->prodotto,'Sliding','staff/_paginator.phtml');
            } 
            
    ?>
     
 </div>
  
     
</div>