<section class="content gallery pad1">

    <h2>FAQ</h2>
    
    <h4 >Come posso cambiare i miei dati?</h4>
    <div class="menu" id="menu1">
        Puoi modificare i tuoi dati personali nella sezione del tuo profilo. Per accederci basta cliccare sul vostro nome in alto a sinistra. Da lì potrete accedere al vostro profilo e modificare i vostri dati personali
    </div>
    
    <h4 >Come ottengo i coupon?</h4>
    <div class="menu" id="menu2">
        Per poter ottenere i coupon è necessario essere un utente registrato. Una volta eseguito l'accesso, basterà accedere alla pagina della promozione desiderata e cliccare sul pulsante "ottieni coupon", dopodichè basterà scaricarlo sul proprio computer.
    </div>
    
    <h4>Come utilizzare il mio coupon?</h4>
    <div class="menu" id="menu3">
        Una volta scaricato il coupon basterà stamparlo ed esibirlo presso la sede dell'azienda
    </div>
    
    <h4>Quali sono le aziende convenzionate?</h4>
    <div class="menu" id="menu4">
        Per vedere l'elenco delle aziende convenzionate <a href="aziende.html">clicca qui</a>
    </div>
    
    <h4>Newsletter: iscrizioni e modifiche</h4>
    <div class="menu" id="menu5">
        Per iscriversi alla newsletter basta...
    </div>    
    <h4>Quando scade il mio coupon?</h4>
    <div class="menu" id="menu6">
        Il coupon emesso è valido per tutta la durata della promozione
    </div>
    <br>
</section>