        
<div class="container">  
    <div class="row">
                            
	      <?php foreach ($this->topCategories as $category) {
		     echo ' <div class="grid_4"> 
                            <div class="banner">
                            <div class="gall_block"> 
                            <div class="bann_title">
                           <h2> <a href=' . $this->url(array('controller' => 'public',
                                                        'action' => 'index',
                                                        'selTopCat' => $category->catId), 
                                                        'default', true) . 
                 '> Sconti su ' . $category->name . '</a></h2></div></div></div></div>';
	      }
	      ?>
	      
	      </div>
	  
	  </div>
<!-- fine sezione laterale -->


