<section class="content gallery pad1">
  <div class="container">
    <div class="row">
    <?php foreach ($this->products as $products) :?>
        <div class="grid_4">
           <div class="gall_block">
                <div class="maxheight">
                    <?php echo $this->productImg($products->image, array('class' => 'imagefrm')) ?>         
                    <div class="gall_bot">
                    <div class="text1"><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Product"><?php echo'<h3 class="title">' . $products->prodotto . '</h3>' ?></a></div> 
                <?php echo  $products->descShort  ?>

		<a class="btn" href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Info Prodotto">More</a>


                    </div>
                </div>
            </div>
        </div>

                            
		  
     <?php endforeach ?>

        </div>
    </div>
</section>