
<ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                            <img src="<?=$this->baseUrl('images/user.png')?>" class="img-thumbnail" />

                            <div class="inner-text">
                                Amministratore :
                            <br />
                                <small><?php echo $this->authInfo('nome') . ' ' . $this->authInfo('cognome'); ?> </small>
                            </div>
                        </div>

                    </li>


                    
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>">  Home </a>
                         
                    </li>
                     <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newaziende',
                        ), 
                        'default', true
                    ); 
                 ?>">Inserisci Azienda </a>
                    </li>
                    
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newfaq',
                        ), 
                        'default', true
                    ); 
                 ?>">Inserisci Faq </a>
                    </li>
                    
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'visualizzaaziende',
                        ), 
                        'default', true
                    ); 
                 ?>">Gestione Aziende </a>
                        
                    </li>
                     
                           
                             <li>
                                <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newstaff',
                        ), 
                        'default', true
                    ); 
                 ?>"></i>Inserisci Staff</a>
                     </li>
                     <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'visualizzastaff',
                        ), 
                        'default', true
                    ); 
                 ?>">Gestione Utenti</a>
                    </li>
                         
                      <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'visualizzastaff',
                        ), 
                        'default', true
                    ); 
                 ?>">Gestione Permessi Staff</a>
                    </li>
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newcategory',
                        ), 
                        'default', true
                    ); 
                 ?>">Inserisci Categoria</a>
                    </li>
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'visualizzacategory',
                        ), 
                        'default', true
                    ); 
                 ?>">Gestione Categorie</a>
                    </li>
                     <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'visualizzafaq',
                        ), 
                        'default', true
                    ); 
                 ?>">Gestire Faq</a>
                    </li>
                    
                     <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'logout',
                        ), 
                        'default', true
                    ); 
                 ?>">Logout</a>
                    </li>
                    
                        </ul>
                    </li>
                   
                    
               