<ul class="sf-menu">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">home</a></li>
		
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Prodotti">prodotti</a>
            <ul>
                <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
                ?>"
                title="Categoria">categorie di prodotti</a></li>
                
                <li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'offerte',
                        ), 
                        'default',true
                ); 
                ?>"
                title="Tipo">tipo di offerte</a></li>
            
            </ul></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'aziende',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Azienda">aziende</a></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Ricerca">ricerca</a></li>
            
            <li><a
            href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'where'), 
                    'default',true
                ); 
                ?>"
            title="Il nostro profilo aziendale">chi siamo</a></li>
          <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Area riservata">Il mio profilo</a></li> 
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Login">login</a></li>          
            
            
		
	
</ul>
