
<ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                            <img src="<?=$this->baseUrl('images/user.png')?>" class="img-thumbnail" />

                            <div class="inner-text">
                               <h3> Benvenuto  <?php echo $this->authInfo('nome_utente') . ' ' . $this->authInfo('cognome'); ?> ! </h3>
                            <br />
                                
                            </div>
                        </div>

                    </li>


                    
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>">  Home </a>
                         
                    </li>
                     
                    
                     
                           
                    <li>
                                <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'visualizzapromo',
                        'idstaff' =>    $this->authInfo('ID_utente')
,
                        ), 
                        'default', true
                        ); 
                        ?>"> Gestione Promozioni </a>
                    </li>
                    <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'newproduct',
                        ), 
                        'default', true
                        ); 
                        ?>">Inserisci </a>
                        
                    </li>
                      <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'profilo',
                        ), 
                        'default', true
                    ); 
                 ?>">Profilo</a>
                    </li>
                     <li>
                        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'logout',
                        ), 
                        'default', true
                    ); 
                 ?>">Logout</a>
                    </li>
                    
                        </ul>
                    </li>
                   
                    
               