<ul class="sf-menu">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">home</a></li>
		
        <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Prodotti">prodotti</a></li>
         
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'aziende',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Azienda">aziende</a></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'ricerca',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Ricerca">ricerca</a></li>
            
            <li><a
            href="<?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'viewstatic',
                    'staticPage' => 'where'), 
                    'default',true
                ); 
                ?>"
            title="Il nostro profilo aziendale">chi siamo</a></li>
         
             <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'login',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Login">login</a></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'registra',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Registra">registrati</a></li> 
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'staff',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
                ?>"
            title="staff">Staff</a></li>
            
            
		
	
</ul>
