<ul class="sf-menu">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">home</a></li>
		
        <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Prodotti">prodotti</a></li>
         
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'aziende',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Azienda">aziende</a></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'ricerca',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Ricerca">ricerca</a></li>
            
            <li><a
            href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'where'), 
                    'default',true
                ); 
                ?>"
            title="Il nostro profilo aziendale">chi siamo</a></li>
         
           <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Registra">profil</a>
            
            <ul>
                <li><a href=" <?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'logout',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Registra">logout</a>
                
                </li>
            
            </ul></li>        
            
            
		
	
</ul>
