<ul class="sf-menu">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">home</a></li>
		
        <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Prodotti">prodotti</a>
            <ul>
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'prodotti',
                    ), 
                    'default',true
                ); 
                ?>"
                title="Categoria">categorie</a>
                    <ul><li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">Abbigliamento</a></li>
                        
                        <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">Cibo</a></li>
                        
                        <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">Sport</a></li></ul>
                
                <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'offerte',
                    ), 
                    'default',true
                    ); 
                    ?>"
                    title="Tipo">offerte</a>
                        <ul><li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">3 x 2</a></li>
                        
                        <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">1 x 2</a></li>
                        
                        <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'prodotti',
                        ), 
                        'default',true
                        ); 
                        ?>"
                        title="Categoria">- 50 %</a></li></ul>
                        
            
                </ul></li>
    
                
              
            
            </li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'aziende',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Azienda">aziende</a></li>
            
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
            ?>"
            title="Ricerca">ricerca</a></li>
            
            <li><a
            href="<?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'viewstatic',
                    'staticPage' => 'where'), 
                    'default',true
                ); 
                ?>"
            title="Il nostro profilo aziendale">chi siamo</a></li>
         
            <li><a href=" <?= $this->url(array(
                    'controller' => 'public',
                    'action'     => 'index',
                    ), 
                    'default',true
                ); 
                ?>"
            title="Login">login</a></li>          
            
            
		
	
</ul>
