<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
</head>
<div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>">CouponMania</a>
            </div>

        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                                        
                    
                        <?= $this->render('_topnavstaff.phtml') ?>
                    
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
      <div id="page-wrapper">
    <div id="page-inner">
            
    <div class="content">
  	  <div class="container">
	  	  <?php echo $this->layout()->content; ?>
        </div>
        </div>
        </div>
        
    </div>
        

    <div id="footer-sec">
        &copy; 2014 YourCompany | Design By : <a href="http://www.binarytheme.com/" target="_blank">BinaryTheme.com</a>
    </div>
    <!-- /. FOOTER  -->

</body>
</html>
