<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript() ; ?>
</head>
<body>
 <section id="stuck_container">
    <div class="container">
      <div class="row">
        <div class="grid_12">
            <h1>
               <a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>">
                <img class="logo" src="<?=$this->baseUrl('images/logo.png')?>" alt="Logo alt">
                </a>
            </h1>  
       
            

	<!-- end #header -->
    <div class="navigation">
            <nav>
                <?= $this->render('_topnavuser.phtml') ?>
            </nav>
    </div>
    <div class="clear"></div>
  </div>
   </div>
     </div>   
</section>

	<!-- end #menu -->
     
    <div class="content">
  	  <div class="container">
	  	  <?php echo $this->layout()->content; ?>
        </div>
        
    </div>
	           
  

	<!-- end #content -->
    <div class="footer">

    <div class="container">
        <div class="container">
            <h3><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>"
		title="faq">FAQ</a></h3>
    
            <ul class="socials">
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>">
                Come posso cambiare i miei dati?</a></li>
                
                
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>" >
                Come ottengo i coupon?</a></li>
                
                
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?> ">
                Come utilizzare il mio coupon?</a></li>
                
                
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>">
                Quali sono le aziende convenzionate?</a></li>
                
                
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>">
                Newsletter: iscrizioni e modifiche</a></li>
                
                
               <li><a href="<?= $this->url(array(
                    'controller' => 'user',
                    'action'     => 'viewstatic',
                    'staticPage' => 'faq'), 
                    'default',true
                ); 
                ?>">
                Quando scade il mio coupon?</a></li>
             </ul>
    </div>
   
    </div>
</div>
</div>
	<!-- end #footer -->
</body>
</html>