 
<section class="content gallery pad1">
    <div class="container">

            <?php if( null == $this->idazienda) :?>

                <?php foreach ($this->aziende as $aziende) :?>
                    <div class="grid_4">
                        <div class="gall_block">
                            <div class="maxheight">
                                <?php echo $this->productImg($aziende->logo, array('class' => 'imagefrm')) ?>         
                                <div class="gall_bot">
                                    <div class="text1"><a href=" <?= $this->url(array('controller' => 'user',
                                                                                        'action' => 'aziende',
                                                                                        'idazienda' => $aziende->P_Iva), 
                                                                                        'default', true); 
                                                                    ?>"
                                        title="Azienda"><?php echo'<h3 class="title">' . $aziende->nome . '</h3>' ?></a></div> 
                                
                                        <a class="btn" href=" <?= $this->url(array('controller' => 'user',
                                                                                    'action' => 'aziende',
                                                                                    'idazienda' => $aziende->P_Iva), 
                                                                                    'default', true); 
                                
                                                                ?>"
                                                                title="InfoAzienda">More</a>


                                    </div>
                                </div>
                            </div>
                        </div>
                                        
                            
                    <?php endforeach ?>

           
            <br>
            <?php if($this->aziende instanceof Zend_Paginator) {
                    echo $this->paginationControl($this->aziende,'Sliding','public/_paginatoraziende.phtml');
                    } 
            ?>


        <?php elseif( !null == $this->idazienda) :?>
                    <?php foreach($this->infoazienda as $infoazienda) :?>
                        <h3>  Nome : <?= $infoazienda->nome ; ?></h3><br>
                        Città :  <?=  $infoazienda->citta  ; ?> <br>
                        Indirizzo :  <?=   $infoazienda->indirizzo  ; ?><br>
                        Descrizione : <?=  $infoazienda->descrizione  ; ?><br>
                        
                        <h3> Promozione : </h3> </br>
                        
                        <?php foreach ($this->promoazienda as $promoazienda) :?>
                            <div class="grid_4">
                            <div class="gall_block">
                                    <div class="maxheight">
                                        <?php echo $this->productImg($promoazienda->immagine, array('class' => 'imagefrm')) ?>         
                                        <div class="gall_bot">
                                        <div class="text1"><a href=" <?= $this->url(array(
                                            'controller' => 'user',
                                            'action'     => 'prodotti',
                                            'idprodotto' => $promoazienda->cod_promozione,
                                            ), 
                                            'default',true
                                        ); 
                                    ?>"
                                    title="Product"><?php echo'<h3 class="title">' . $promoazienda->prodotto . '</h3>' ?></a></div> 
                                    <?php echo  $promoazienda->descrizione_prom  ?><br>
                                     Tipo di promozione : <?= $promoazienda->name ; ?><br>
                                    Azienda :<?= $promoazienda->nome ;?><br>

                                    <a class="btn" href=" <?= $this->url(array(
                                            'controller' => 'user',
                                            'action'     => 'prodotti',
                                            'idprodotto' => $promoazienda->cod_promozione,

                                            ), 
                                            'default',true
                                        ); 
                                    ?>"
                                    title="Info Prodotto">More</a>


                                        </div>
                                    </div>
                                </div>
                                <br>
                            </div>
            

                            
		  
                        <?php endforeach ?>
     

                       
                    <?php endforeach ?>
                
 
        <?php endif ?>
                
    </div>
</section>




