<section class="content">
  <div class="container">
    <div class="row">
      <div class="grid_8">
        <h2>Nome Azienda</h2>
        <?php   echo $this->idazienda ?>
        <img src="images/page3_img1.jpg" alt="" class="img_inner fleft inn__1">
        <div class="extra_wrapper">
          <h2>Informazioni azienda</h2>
          <p class="text1 tx__1"> Praesenterto faucibus maleada faucibusnec laeetert metus id laoreet </p>
          <p class="text1 tx__1">Nullam consectetur orci sed nulla facilisisequaterto. Curabitur vel lorem sit amet nulla perermentum. Aliquam nibh ante, egestas id dictum a, commodo luctus libero.</p>
          
        </div>
        <div class="clear"></div>
        <h2> Promozioni Attive</h2>
        <div class="text1 tx__1"><a href="#">Promozione1</a></div>
        <div class="text1 tx__1"><a href="#">Promozione2</a></div>
        <div class="text1 tx__1"><a href="#">Promozione3</a></div>
        <a href="#" class="btn">more</a>
      </div>
      <div class="grid_4">
        
       
      </div>
    </div>
  </div>
</section>




