<div class="static">
 <h3>Area Amministratore</h3>
 <h2> Benvenuto  <?php echo $this->authInfo('nome') . ' ' . $this->authInfo('cognome'); ?> ! </h2>
 <p>Seleziona la funzione da attivare</p>
 
 
  <div class="grid_4">
            <div class="gall_block">
                        <div class="gall_bot">
                            <a href='<?= $this->url(array('controller' => 'admin',
                                                        'action' => 'statistica',
                                                                 'mod'=> 1,), 
                                                                'default', true); ?>
                                        '>
                            <div class="text1"><h1>Numero di Coupon Emessi</h1></div> <br> </a>
                            <hr>
                            <div> <h1><?= $this->coupon ?></h1></div>


                        </div>
            </div>
    </div>

    <div class="grid_4">
                <div class="gall_block">
                            <div class="gall_bot">
                                <a href='<?= $this->url(array('controller' => 'admin',
                                                                'action' => 'statistica',
                                                                'mod'=> 0,), 'default', true); ?>
                                        '>
                                <div class="text1"><h1>Numero di Utenti registrati</h1></div> <br> </a>
                                <hr>
                                <div> <h1><?= $this->utenti ?></h1></div>


                            </div>
                </div>
    </div>
    
  
     <div class="grid_4">
                <div class="gall_block">
                            <div class="gall_bot">
                                <div class="text1"><h1>Numero di Aziende iscritta</h1></div> <br>
                                <hr>
                                <div> <h1><?= $this->aziende ?></h1></div>


                            </div>
                </div>
    </div>

</div>