<div class="static">
 <h3>Utenti</h3>
 <div>
 <?php 
 echo '<table class="tabella">';
	echo "<tr><th>ID Utente</th><th>Nome</th><th>Cognome</th><th>Ruolo</th><th>Username</th><th>Gestione Permessi</th></tr>";
  foreach ($this->staff as $staff) {
      echo "<tr><td>".$staff->ID_utente."</td>"
              . "<td>".$staff->nome_utente."</td>"
              . "<td>".$staff->cognome."</td>"             
              . "<td>".$staff->role."</td>"
              . "<td>".$staff->username."</td>"              
              . "<td><a href=" . $this->url(array('controller' => 'admin',
                                                        'action' => 'visualizzapermessi',
                                                        'idstaff'=> $staff->ID_utente), 
                                                        'default', true) ."><img class='icon' src='".$this->baseUrl('images/chiave.png')."' alt='Gestione Permessi'></a></td>";
              
                                                        
  }
 echo '</table>';
 ?>
     
 </div>
 
</div>