<div class="static">
 <h3>Utenti</h3>
 <div>
 <?php 
  
 echo '<table class="tabella">';
	echo "<tr><th>Nome</th><th>Cancella</th></tr>";
  foreach ($this->permessi as $permessi) {
      echo "<tr><td>".$permessi->nome."</td>"                       
              . "<td><a href=" . $this->url(array('controller' => 'admin',
                                                        'action' => 'cancellapermessi',
                                                        'idazienda'=> $permessi->P_Iva,
                                                        'idutente' => $permessi->ID_utente), 
                                                        'default', true) ."><img class='icon' src='".$this->baseUrl('images/cancella.png')."' alt='Cancella'></a></td></tr>";
  }
  echo '</table><br> <br>';
  
  echo "<a href=" . $this->url(array('controller' => 'admin',
                                                        'action' => 'newstaffpermessi',
                                                        'idstaff' => $this->idstaff), 
                                                        'default', true) ."><img class='icon' src='".$this->baseUrl('images/piu.png')."' alt='Aggiungi Permesso'>Aggiungi una nuova azienda</a>";
  
  ?>
  


     
 </div>
 
</div>