<div class="static">
 <h3>Utenti</h3>
 <div>
 

  <table class="tabella">
 <tr><th>Nome</th><th>Cancella</th></tr>
  <?php foreach ($this->permessi as $permessi) :?>
      <tr><td>"<?=$permessi->nome ?></td>                     
        <td><a href="<?= $this->url(array('controller' => 'admin',
                                                        'action' => 'cancellapermessi',
                                                        'idazienda'=> $permessi->P_Iva), 
                                                        'default', true) ?>"><img class='icon' src='<?=$this->baseUrl('images/cancella.png')?>' alt='Cancella'></a></td></tr>";
 <?php endforeach ?>
 </table>
 
  <br><br>
  
  <a href="<?= $this->url(array('controller' => 'admin',
                                'action' => 'newstaffpermessi',
                                'idstaff'=> $permessi->ID_utente), 
                                'default', true) ?>"><img class='icon' src='<?=$this->baseUrl('images/modifica.png')?>' alt='Aggiungi Azienda'>Aggiungere uno permesso </a>
  

     
 </div>
 
</div>